### ISSUE TITLE
z-nomp stratum server

### ISSUE THREAD

**Issue by tecnoinfoch** [cryptocoinjs/base-x#43]
you help me?

/home/pool/zcash/znomp/node_modules/base-x/index.js:52
    if (string.length === 0) return Buffer.allocUnsafe(0)
              ^

TypeError: Cannot read property 'length' of undefined
    at decodeUnsafe (/home/pool/zcash/znomp/node_modules/base-x/index.js:52:15)
    at Object.decode (/home/pool/zcash/znomp/node_modules/base-x/index.js:81:15)
    at Object.decode (/home/pool/zcash/znomp/node_modules/bs58check/index.js:44:23)
    at Object.fromBase58Check (/home/pool/zcash/znomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/transactions.js:97:52)
    at new BlockTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/pool.js:588:66
    at itemFinished (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:169:17

**Comment by dcousens** [comment]
The parameter `string` needs to be a `String`,  you are passing `undefined.

**Comment by tecnoinfoch** [comment]
Ok but what is and where is the mistake?

**Comment by dcousens** [comment]
The mistake is you are passing `undefined`.

Where

> at Object.exports.createGeneration (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/transactions.js:97:52)
> at new BlockTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
> at JobManager.processTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
> at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/pool.js:588:66
> at itemFinished (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:155:36)
> at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:169:17
